// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(CosmeticosContext))]
    [Migration("20250920155824_NuevoInicio")]
    partial class NuevoInicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Service.Models.MenuRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int>("menuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("menuId");

                    b.ToTable("MenuRol");
                });

            modelBuilder.Entity("Service.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = 4,
                            Descripcion = "Crema para hidratar la piel",
                            IsDeleted = false,
                            Nombre = "Crema Hidratante",
                            Precio = 32000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Categoria = 1,
                            Descripcion = "Efecto mate",
                            IsDeleted = false,
                            Nombre = "Labial liquido",
                            Precio = 12000m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 3,
                            Categoria = 2,
                            Descripcion = "Estilo highlight",
                            IsDeleted = false,
                            Nombre = "Sombras",
                            Precio = 18.00m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 4,
                            Categoria = 3,
                            Descripcion = "Efecto cracheado",
                            IsDeleted = false,
                            Nombre = "Esmalte de uñas",
                            Precio = 30.00m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 5,
                            Categoria = 0,
                            Descripcion = "De estilo floral",
                            IsDeleted = false,
                            Nombre = "Perfume",
                            Precio = 22.00m,
                            Stock = 90
                        });
                });

            modelBuilder.Entity("Service.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "amada@gmail.com",
                            IsDeleted = false,
                            Nombre = "Amanda",
                            Password = "amanda123",
                            Rol = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "juana@gmail.com",
                            IsDeleted = false,
                            Nombre = "Juana",
                            Password = "juana123",
                            Rol = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "pedro@gmail.com",
                            IsDeleted = false,
                            Nombre = "Pedro",
                            Password = "pedro123",
                            Rol = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "maria@gmail.com",
                            IsDeleted = false,
                            Nombre = "Maria",
                            Password = "maria123",
                            Rol = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "luisa@gmail.com",
                            IsDeleted = false,
                            Nombre = "Luisa",
                            Password = "luisa123",
                            Rol = 4
                        },
                        new
                        {
                            Id = 5,
                            Email = "carlos@gmail.com",
                            IsDeleted = false,
                            Nombre = "Carlos",
                            Password = "carlos123",
                            Rol = 4
                        });
                });

            modelBuilder.Entity("Service.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 2,
                            Fecha = new DateTime(2025, 9, 20, 12, 58, 22, 506, DateTimeKind.Local).AddTicks(7227),
                            IsDeleted = false,
                            Nombre = "",
                            PrecioTotal = 150.00m
                        },
                        new
                        {
                            Id = 2,
                            Estado = 1,
                            Fecha = new DateTime(2025, 9, 20, 12, 58, 22, 506, DateTimeKind.Local).AddTicks(7238),
                            IsDeleted = false,
                            Nombre = "",
                            PrecioTotal = 200.00m
                        },
                        new
                        {
                            Id = 3,
                            Estado = 3,
                            Fecha = new DateTime(2025, 9, 20, 12, 58, 22, 506, DateTimeKind.Local).AddTicks(7241),
                            IsDeleted = false,
                            Nombre = "",
                            PrecioTotal = 300.00m
                        },
                        new
                        {
                            Id = 4,
                            Estado = 2,
                            Fecha = new DateTime(2025, 9, 20, 12, 58, 22, 506, DateTimeKind.Local).AddTicks(7244),
                            IsDeleted = false,
                            Nombre = "",
                            PrecioTotal = 400.00m
                        },
                        new
                        {
                            Id = 5,
                            Estado = 1,
                            Fecha = new DateTime(2025, 9, 20, 12, 58, 22, 506, DateTimeKind.Local).AddTicks(7247),
                            IsDeleted = false,
                            Nombre = "",
                            PrecioTotal = 500.00m
                        });
                });

            modelBuilder.Entity("Service.Models.VentaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VentaDetalles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 2,
                            IsDeleted = false,
                            PrecioUnitario = 32000m,
                            ProductoNombre = "Prefume",
                            VentaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1,
                            IsDeleted = false,
                            PrecioUnitario = 12000m,
                            ProductoNombre = "Crema",
                            VentaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 3,
                            IsDeleted = false,
                            PrecioUnitario = 18000m,
                            ProductoNombre = "Labial",
                            VentaId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 1,
                            IsDeleted = false,
                            PrecioUnitario = 30000m,
                            ProductoNombre = "Sombras",
                            VentaId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 2,
                            IsDeleted = false,
                            PrecioUnitario = 22000m,
                            ProductoNombre = "Esmalte",
                            VentaId = 3
                        });
                });

            modelBuilder.Entity("Service.Models.MenuRol", b =>
                {
                    b.HasOne("Service.Models.Menu", "menu")
                        .WithMany()
                        .HasForeignKey("menuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menu");
                });
#pragma warning restore 612, 618
        }
    }
}
