// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(CosmeticosContext))]
    [Migration("20250930231928_Recategorizacion")]
    partial class Recategorizacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Nombre = "Perfumería"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Nombre = "Cuidado de la piel"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Nombre = "Maquillaje"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Nombre = "Cuidado del cabello"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Nombre = "Cuidado corporal"
                        });
                });

            modelBuilder.Entity("Service.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Acceso al módulo de ventas",
                            IsDeleted = false,
                            Nombre = "Gestión de Ventas"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Acceso al módulo de productos",
                            IsDeleted = false,
                            Nombre = "Gestión de Productos"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Acceso a reportes del sistema",
                            IsDeleted = false,
                            Nombre = "Reportes"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Historial de compras del cliente",
                            IsDeleted = false,
                            Nombre = "Historial"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Gestión de usuarios del sistema",
                            IsDeleted = false,
                            Nombre = "Usuarios"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Detalles de las ventas",
                            IsDeleted = false,
                            Nombre = "Detalles de Venta"
                        });
                });

            modelBuilder.Entity("Service.Models.MenuRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            MenuId = 1,
                            Rol = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            MenuId = 2,
                            Rol = 1
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            MenuId = 3,
                            Rol = 1
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            MenuId = 4,
                            Rol = 1
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            MenuId = 5,
                            Rol = 1
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            MenuId = 6,
                            Rol = 1
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            MenuId = 1,
                            Rol = 2
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            MenuId = 2,
                            Rol = 2
                        },
                        new
                        {
                            Id = 13,
                            IsDeleted = false,
                            MenuId = 6,
                            Rol = 2
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            MenuId = 2,
                            Rol = 3
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            MenuId = 4,
                            Rol = 3
                        });
                });

            modelBuilder.Entity("Service.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Perfume floral",
                            IsDeleted = false,
                            Nombre = "Perfume",
                            Precio = 32000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descripcion = "Crema hidratante",
                            IsDeleted = false,
                            Nombre = "Crema",
                            Precio = 12000m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descripcion = "Labial rojo",
                            IsDeleted = false,
                            Nombre = "Labial",
                            Precio = 18000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Descripcion = "Paleta de sombras",
                            IsDeleted = false,
                            Nombre = "Sombras",
                            Precio = 30000m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 5,
                            Descripcion = "Esmalte de uñas",
                            IsDeleted = false,
                            Nombre = "Esmalte",
                            Precio = 22000m,
                            Stock = 40
                        });
                });

            modelBuilder.Entity("Service.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Email = "amada@gmail.com",
                            IsDeleted = false,
                            Nombre = "Amanda",
                            Password = "amanda123",
                            Rol = 1
                        },
                        new
                        {
                            id = 6,
                            Email = "juana@gmail.com",
                            IsDeleted = false,
                            Nombre = "Juana",
                            Password = "juana123",
                            Rol = 2
                        },
                        new
                        {
                            id = 2,
                            Email = "pedro@gmail.com",
                            IsDeleted = false,
                            Nombre = "Pedro",
                            Password = "pedro123",
                            Rol = 2
                        },
                        new
                        {
                            id = 3,
                            Email = "maria@gmail.com",
                            IsDeleted = false,
                            Nombre = "Maria",
                            Password = "maria123",
                            Rol = 2
                        },
                        new
                        {
                            id = 4,
                            Email = "luisa@gmail.com",
                            IsDeleted = false,
                            Nombre = "Luisa",
                            Password = "luisa123",
                            Rol = 3
                        },
                        new
                        {
                            id = 5,
                            Email = "carlos@gmail.com",
                            IsDeleted = false,
                            Nombre = "Carlos",
                            Password = "carlos123",
                            Rol = 3
                        });
                });

            modelBuilder.Entity("Service.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 2,
                            Fecha = new DateTime(2025, 9, 30, 20, 19, 25, 350, DateTimeKind.Local).AddTicks(1747),
                            IsDeleted = false,
                            Nombre = "",
                            PrecioTotal = 150.00m
                        },
                        new
                        {
                            Id = 2,
                            Estado = 1,
                            Fecha = new DateTime(2025, 9, 30, 20, 19, 25, 350, DateTimeKind.Local).AddTicks(1755),
                            IsDeleted = false,
                            Nombre = "",
                            PrecioTotal = 200.00m
                        },
                        new
                        {
                            Id = 3,
                            Estado = 3,
                            Fecha = new DateTime(2025, 9, 30, 20, 19, 25, 350, DateTimeKind.Local).AddTicks(1759),
                            IsDeleted = false,
                            Nombre = "",
                            PrecioTotal = 300.00m
                        },
                        new
                        {
                            Id = 4,
                            Estado = 2,
                            Fecha = new DateTime(2025, 9, 30, 20, 19, 25, 350, DateTimeKind.Local).AddTicks(1761),
                            IsDeleted = false,
                            Nombre = "",
                            PrecioTotal = 400.00m
                        },
                        new
                        {
                            Id = 5,
                            Estado = 1,
                            Fecha = new DateTime(2025, 9, 30, 20, 19, 25, 350, DateTimeKind.Local).AddTicks(1764),
                            IsDeleted = false,
                            Nombre = "",
                            PrecioTotal = 500.00m
                        });
                });

            modelBuilder.Entity("Service.Models.VentaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VentaDetalles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 2,
                            IsDeleted = false,
                            PrecioUnitario = 32000m,
                            ProductoNombre = "Prefume",
                            VentaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1,
                            IsDeleted = false,
                            PrecioUnitario = 12000m,
                            ProductoNombre = "Crema",
                            VentaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 3,
                            IsDeleted = false,
                            PrecioUnitario = 18000m,
                            ProductoNombre = "Labial",
                            VentaId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 1,
                            IsDeleted = false,
                            PrecioUnitario = 30000m,
                            ProductoNombre = "Sombras",
                            VentaId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 2,
                            IsDeleted = false,
                            PrecioUnitario = 22000m,
                            ProductoNombre = "Esmalte",
                            VentaId = 3
                        });
                });

            modelBuilder.Entity("Service.Models.MenuRol", b =>
                {
                    b.HasOne("Service.Models.Menu", "menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menu");
                });

            modelBuilder.Entity("Service.Models.Producto", b =>
                {
                    b.HasOne("Service.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
